name: books_api
description: "Books API consumption"


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  shared_preferences: 2.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/